
EMBEDDING_DIM = 50

MAX_SEQUENCE_LENGTH = 12
VALIDATION_SPLIT = 0.1


RATE_DROP_LSTM = 0.3
RATE_DROP_DENSE = 0.4
NUMBER_LSTM = 200
NUMBER_DENSE_UNITS = 100
ACTIVATION_FUNCTION = 'relu'


siamese_config = {
	'EMBEDDING_DIM': EMBEDDING_DIM,
	'MAX_SEQUENCE_LENGTH' : MAX_SEQUENCE_LENGTH,
	'VALIDATION_SPLIT': VALIDATION_SPLIT,
	'RATE_DROP_LSTM': RATE_DROP_LSTM,
	'RATE_DROP_DENSE': RATE_DROP_DENSE,
	'NUMBER_LSTM': NUMBER_LSTM,
	'NUMBER_DENSE_UNITS': NUMBER_DENSE_UNITS,
	'ACTIVATION_FUNCTION': ACTIVATION_FUNCTION
}